### ISSUE TITLE
installing via pip does not work

### ISSUE THREAD

**Issue by naamat** [semantic-health/allennlp-multi-label#39]
Hi,
I tried to use pip to install but it did not work.
We are working with conda so using poetry will be problematic for us.
Could you add this project to pypi.org or add a setup.py to install from git?

Thanks,
Naama

**Comment by JohnGiorgi** [comment]
@MichalMalyska If you guys want to maintain this on semantic-health's PyPi, you will need to:

1. `git fetch ; git pull`
2. `poetry build`
3. `poetry publish`

Then `0.1.0` will be available to pip install. I just need until the end of the day to tie up some loose ends. I will mark the `0.1.0` release when it is ready.

**Comment by JohnGiorgi** [comment]
@MichalMalyska Will you let me know which route works better for you (I upload or you upload)?

**Comment by JohnGiorgi** [comment]
@naamat We are running into an issue because this repo currently installs AllenNLP from source (we need master) but PyPI won't let us have a dependency on something that is not on PyPI. We will have to wait until AllenNLP releases `1.2.0`.

What if we generated a `requirements.txt` for you? Any reason you can't `git clone` and `pip install`?

**Comment by JohnGiorgi** [comment]
I am going to close this! Please let us know if you have any more questions regarding the install. Once AllenNLP releases 1.2.0 on pip, we will upload this package to PyPI.

**Comment by MichalMalyska** [comment]
@JohnGiorgi just as we close this Allen 1.2.0 gets released with all the changes. I will try to get the pip install working asap

**Comment by JohnGiorgi** [comment]
Doesn't look like it is live on pip yet! I'll will bump the dependency when it is and the version of this repo and let you know.

We can upload this to pip as version 0.1.1.

**Comment by JohnGiorgi** [comment]
Ah, the release is causing me all sorts of issues. They all seem to resolve around `dataclasses`:

```python
  SolverProblemError

  The current project's Python requirement (3.8.5) is not compatible with some of the required packages Python requirement:
    - dataclasses requires Python >=3.6, <3.7, so it will not be satisfied for Python 3.8.5
  
  Because no versions of allennlp match >1.2.0,<2.0.0
   and allennlp (1.2.0) depends on torch (>=1.6.0,<1.8.0), allennlp (>=1.2.0,<2.0.0) requires torch (>=1.6.0,<1.8.0).
  And because no versions of torch match >=1.6.0,<1.7.0 || >1.7.0,<1.8.0
   and torch (1.7.0) depends on dataclasses (*), allennlp (>=1.2.0,<2.0.0) requires dataclasses (*).
  Because dataclasses (0.7) requires Python >=3.6, <3.7
   and no versions of dataclasses match !=0.7, dataclasses is forbidden.
  Thus, allennlp is forbidden.
  So, because allennlp-multi-label depends on allennlp (^1.2.0), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For dataclasses, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```
